# Generated by Django 5.0.1 on 2024-02-22 13:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManageProject',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('demo_link', models.CharField(max_length=2500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid3, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
