# Generated by Django 5.0.1 on 2024-02-23 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_message_profile_project_skill_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='id',
            new_name='msg_id',
        ),
    ]
