# Generated by Django 5.0.1 on 2024-02-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0008_manageproject_project_review_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageproject',
            name='tag',
            field=models.ManyToManyField(blank=True, to='projectapp.tag'),
        ),
        migrations.AlterField(
            model_name='project_review',
            name='value',
            field=models.CharField(choices=[('Like', 'Liked Post'), ('Unlike', 'Unliked Post')], max_length=200),
        ),
    ]
