# Generated by Django 5.0.1 on 2024-02-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_manageproject_tag_alter_project_review_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageproject',
            name='ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='manageproject',
            name='reacts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project_review',
            name='value',
            field=models.CharField(choices=[('Unlike', 'Unliked Post'), ('Like', 'Liked Post')], max_length=200),
        ),
    ]
