# Generated by Django 5.0.1 on 2024-03-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0010_manageproject_ratio_manageproject_reacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageproject',
            name='featured_img',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project_review',
            name='value',
            field=models.CharField(choices=[('Like', 'Liked Post'), ('Unlike', 'Unliked Post')], max_length=200),
        ),
    ]
