# Generated by Django 5.0.1 on 2024-03-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0012_alter_manageproject_featured_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manageproject',
            name='featured_img',
        ),
        migrations.AlterField(
            model_name='project_review',
            name='value',
            field=models.CharField(choices=[('Like', 'Liked Post'), ('Unlike', 'Unliked Post')], max_length=200),
        ),
    ]
