# Generated by Django 5.0.1 on 2024-03-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0014_manageproject_featured_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageproject',
            name='demo_link',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='project_review',
            name='value',
            field=models.CharField(choices=[('Like', 'Liked Post'), ('Unlike', 'Unliked Post')], max_length=200),
        ),
    ]
