# Generated by Django 5.0.1 on 2024-03-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0018_alter_project_review_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_review',
            name='value',
            field=models.CharField(choices=[('Like', 'Liked Post'), ('Unlike', 'Unliked Post')], max_length=200),
        ),
    ]
