# Generated by Django 5.0.1 on 2024-03-07 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0019_alter_project_review_value'),
        ('userapp', '0003_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageproject',
            name='projectowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.profile'),
        ),
    ]
