# Generated by Django 5.0.1 on 2024-03-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0020_manageproject_projectowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_review',
            name='value',
            field=models.CharField(choices=[('Unlike', 'Unliked Post'), ('Like', 'Liked Post')], max_length=200),
        ),
    ]
