# Generated by Django 5.0.1 on 2024-04-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0023_alter_project_review_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manageproject',
            name='ratio',
        ),
        migrations.RemoveField(
            model_name='manageproject',
            name='reacts',
        ),
        migrations.DeleteModel(
            name='Project_Review',
        ),
    ]
