# Generated by Django 5.0.1 on 2024-03-07 05:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('Name', models.CharField(blank=True, max_length=250, null=True)),
                ('Email', models.EmailField(blank=True, max_length=500, null=True)),
                ('About', models.CharField(blank=True, max_length=500, null=True)),
                ('Bio', models.TextField(blank=True, null=True)),
                ('X_link', models.CharField(blank=True, max_length=500, null=True)),
                ('Instagram_link', models.CharField(blank=True, max_length=500, null=True)),
                ('Profile_img', models.ImageField(blank=True, default='Profiles/OIP.jpg', null=True, upload_to='Profiles/')),
                ('Github_link', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
