# Generated by Django 5.0.1 on 2024-03-07 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Name',
            new_name='name',
        ),
    ]
