# Generated by Django 5.0.1 on 2024-04-04 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
    ]
