# Generated by Django 5.0.1 on 2024-04-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_remove_message_email_remove_message_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveField(
            model_name='skills',
            name='desc',
        ),
    ]
